/**
 * 12-season color system reference data. Used by the mock color-analysis API
 * and by the season picker / palette editor UI in both modes.
 */
import type { ColorSeason, PaletteColor } from '@hemline/contracts';

export interface SeasonInfo {
  season: ColorSeason;
  label: string;
  tagline: string;
  palette: PaletteColor[];
  avoid: PaletteColor[];
}

export const SEASONS: Record<ColorSeason, SeasonInfo> = {
  bright_winter: {
    season: 'bright_winter',
    label: 'Bright Winter',
    tagline: 'High contrast, cool and electric',
    palette: [
      { hex: '#E4002B', name: 'true red' },
      { hex: '#D5006D', name: 'magenta' },
      { hex: '#0057B8', name: 'cobalt' },
      { hex: '#00A3E0', name: 'ice blue' },
      { hex: '#009775', name: 'emerald' },
      { hex: '#6E3FA3', name: 'violet' },
      { hex: '#101820', name: 'jet black' },
      { hex: '#FFFFFF', name: 'pure white' },
      { hex: '#F1EB9C', name: 'icy lemon' },
      { hex: '#C6007E', name: 'fuchsia' },
    ],
    avoid: [
      { hex: '#C4A484', name: 'camel' },
      { hex: '#8A9A5B', name: 'moss' },
      { hex: '#D2B48C', name: 'tan' },
      { hex: '#B87333', name: 'copper' },
      { hex: '#F5DEB3', name: 'wheat' },
    ],
  },
  true_winter: {
    season: 'true_winter',
    label: 'True Winter',
    tagline: 'Cool, deep and crisp',
    palette: [
      { hex: '#0C2340', name: 'navy' },
      { hex: '#A6093D', name: 'crimson' },
      { hex: '#001489', name: 'royal blue' },
      { hex: '#00594C', name: 'pine' },
      { hex: '#84329B', name: 'amethyst' },
      { hex: '#101820', name: 'black' },
      { hex: '#FFFFFF', name: 'white' },
      { hex: '#C8102E', name: 'cherry' },
      { hex: '#71C5E8', name: 'glacier' },
      { hex: '#63666A', name: 'charcoal' },
    ],
    avoid: [
      { hex: '#E8B004', name: 'mustard' },
      { hex: '#CC7722', name: 'ochre' },
      { hex: '#F5F5DC', name: 'beige' },
      { hex: '#FA8072', name: 'salmon' },
      { hex: '#808000', name: 'olive' },
    ],
  },
  dark_winter: {
    season: 'dark_winter',
    label: 'Dark Winter',
    tagline: 'Deep, cool and dramatic',
    palette: [
      { hex: '#3C1053', name: 'aubergine' },
      { hex: '#5D0A2C', name: 'black cherry' },
      { hex: '#123524', name: 'forest' },
      { hex: '#101820', name: 'black' },
      { hex: '#0C2340', name: 'midnight' },
      { hex: '#7C2855', name: 'mulberry' },
      { hex: '#006272', name: 'deep teal' },
      { hex: '#9D2235', name: 'garnet' },
      { hex: '#D6D2C4', name: 'bone' },
      { hex: '#425563', name: 'slate' },
    ],
    avoid: [
      { hex: '#FFE4B5', name: 'peach' },
      { hex: '#F0DC82', name: 'buttercream' },
      { hex: '#FFB6C1', name: 'powder pink' },
      { hex: '#E9967A', name: 'coral' },
      { hex: '#D2B48C', name: 'tan' },
    ],
  },
  bright_spring: {
    season: 'bright_spring',
    label: 'Bright Spring',
    tagline: 'Warm, clear and vivid',
    palette: [
      { hex: '#FF3EB5', name: 'hot pink' },
      { hex: '#FF6720', name: 'tangerine' },
      { hex: '#00B140', name: 'kelly green' },
      { hex: '#00A9E0', name: 'turquoise' },
      { hex: '#FDD757', name: 'daffodil' },
      { hex: '#E4002B', name: 'poppy' },
      { hex: '#963CBD', name: 'orchid' },
      { hex: '#FFFFFF', name: 'white' },
      { hex: '#101820', name: 'ink' },
      { hex: '#FF8DA1', name: 'watermelon' },
    ],
    avoid: [
      { hex: '#9A8478', name: 'taupe' },
      { hex: '#708090', name: 'slate gray' },
      { hex: '#800020', name: 'burgundy' },
      { hex: '#D6D2C4', name: 'greige' },
      { hex: '#4B3621', name: 'dark brown' },
    ],
  },
  true_spring: {
    season: 'true_spring',
    label: 'True Spring',
    tagline: 'Warm, fresh and golden',
    palette: [
      { hex: '#FFB81C', name: 'marigold' },
      { hex: '#FF8200', name: 'apricot' },
      { hex: '#74AA50', name: 'leaf green' },
      { hex: '#00B0B9', name: 'aqua' },
      { hex: '#FE5000', name: 'coral red' },
      { hex: '#F2C75C', name: 'honey' },
      { hex: '#EF60A3', name: 'peony' },
      { hex: '#FFCD00', name: 'sunflower' },
      { hex: '#9E652E', name: 'caramel' },
      { hex: '#FFF4E0', name: 'ivory' },
    ],
    avoid: [
      { hex: '#101820', name: 'black' },
      { hex: '#0C2340', name: 'navy' },
      { hex: '#84329B', name: 'cool purple' },
      { hex: '#63666A', name: 'ash gray' },
      { hex: '#5D0A2C', name: 'wine' },
    ],
  },
  light_spring: {
    season: 'light_spring',
    label: 'Light Spring',
    tagline: 'Light, warm and luminous',
    palette: [
      { hex: '#FDBE87', name: 'peach' },
      { hex: '#F8E08E', name: 'buttercup' },
      { hex: '#A7E6D7', name: 'seafoam' },
      { hex: '#FFA3B5', name: 'shell pink' },
      { hex: '#9BCBEB', name: 'sky' },
      { hex: '#C5E86C', name: 'spring green' },
      { hex: '#FFF4E0', name: 'cream' },
      { hex: '#FF8674', name: 'melon' },
      { hex: '#D3F0EE', name: 'mint frost' },
      { hex: '#C6A05E', name: 'light camel' },
    ],
    avoid: [
      { hex: '#101820', name: 'black' },
      { hex: '#5D0A2C', name: 'black cherry' },
      { hex: '#3C1053', name: 'aubergine' },
      { hex: '#123524', name: 'forest' },
      { hex: '#63666A', name: 'charcoal' },
    ],
  },
  light_summer: {
    season: 'light_summer',
    label: 'Light Summer',
    tagline: 'Light, cool and airy',
    palette: [
      { hex: '#9BB8D3', name: 'powder blue' },
      { hex: '#DCC7DF', name: 'wisteria' },
      { hex: '#F8C1CC', name: 'rose quartz' },
      { hex: '#A2D4C6', name: 'sea glass' },
      { hex: '#C9CDE2', name: 'periwinkle' },
      { hex: '#E3E8EA', name: 'cloud' },
      { hex: '#94A9B8', name: 'dove blue' },
      { hex: '#D390BC', name: 'lilac rose' },
      { hex: '#B4C79C', name: 'celadon' },
      { hex: '#7A99AC', name: 'harbor' },
    ],
    avoid: [
      { hex: '#FF6720', name: 'orange' },
      { hex: '#101820', name: 'black' },
      { hex: '#B87333', name: 'copper' },
      { hex: '#E8B004', name: 'mustard' },
      { hex: '#9D2235', name: 'brick' },
    ],
  },
  true_summer: {
    season: 'true_summer',
    label: 'True Summer',
    tagline: 'Cool, soft and refined',
    palette: [
      { hex: '#5B7F95', name: 'french blue' },
      { hex: '#C4A4A7', name: 'dusty rose' },
      { hex: '#7965B2', name: 'iris' },
      { hex: '#4E87A0', name: 'lake' },
      { hex: '#9E4877', name: 'raspberry' },
      { hex: '#8E9FBC', name: 'chambray' },
      { hex: '#546F7A', name: 'blue spruce' },
      { hex: '#D8D7DF', name: 'oyster' },
      { hex: '#6E7CA0', name: 'twilight' },
      { hex: '#B76BA3', name: 'mauve orchid' },
    ],
    avoid: [
      { hex: '#FF8200', name: 'apricot' },
      { hex: '#FFCD00', name: 'gold' },
      { hex: '#B87333', name: 'rust' },
      { hex: '#101820', name: 'black' },
      { hex: '#74AA50', name: 'warm green' },
    ],
  },
  soft_summer: {
    season: 'soft_summer',
    label: 'Soft Summer',
    tagline: 'Muted, cool and misty',
    palette: [
      { hex: '#8C9BAB', name: 'fog blue' },
      { hex: '#A38FAE', name: 'heather' },
      { hex: '#8F9E8B', name: 'eucalyptus' },
      { hex: '#B48A8F', name: 'rose taupe' },
      { hex: '#6B7F94', name: 'storm' },
      { hex: '#94727D', name: 'plum smoke' },
      { hex: '#A9A48E', name: 'sage gray' },
      { hex: '#54626F', name: 'graphite blue' },
      { hex: '#C3B5AC', name: 'mushroom' },
      { hex: '#7E6D77', name: 'dried lavender' },
    ],
    avoid: [
      { hex: '#FF3EB5', name: 'hot pink' },
      { hex: '#FF6720', name: 'tangerine' },
      { hex: '#FFCD00', name: 'bright gold' },
      { hex: '#101820', name: 'black' },
      { hex: '#00B140', name: 'kelly green' },
    ],
  },
  soft_autumn: {
    season: 'soft_autumn',
    label: 'Soft Autumn',
    tagline: 'Muted, warm and earthy',
    palette: [
      { hex: '#C4A484', name: 'camel' },
      { hex: '#8A9A5B', name: 'moss' },
      { hex: '#B5651D', name: 'cinnamon' },
      { hex: '#A9805B', name: 'toffee' },
      { hex: '#8D6E63', name: 'cocoa rose' },
      { hex: '#6B8E7B', name: 'sage teal' },
      { hex: '#C48A69', name: 'terracotta' },
      { hex: '#9C8AA5', name: 'smoky violet' },
      { hex: '#D9C1A3', name: 'oat' },
      { hex: '#7C6C57', name: 'driftwood' },
    ],
    avoid: [
      { hex: '#E4002B', name: 'true red' },
      { hex: '#FFFFFF', name: 'stark white' },
      { hex: '#0057B8', name: 'cobalt' },
      { hex: '#D5006D', name: 'magenta' },
      { hex: '#101820', name: 'black' },
    ],
  },
  true_autumn: {
    season: 'true_autumn',
    label: 'True Autumn',
    tagline: 'Warm, rich and golden',
    palette: [
      { hex: '#B87333', name: 'copper' },
      { hex: '#808000', name: 'olive' },
      { hex: '#C1440E', name: 'rust' },
      { hex: '#E8B004', name: 'mustard' },
      { hex: '#7B3F00', name: 'chestnut' },
      { hex: '#996515', name: 'bronze' },
      { hex: '#B94E31', name: 'paprika' },
      { hex: '#556B2F', name: 'dark olive' },
      { hex: '#D2691E', name: 'pumpkin' },
      { hex: '#F5DEB3', name: 'wheat' },
    ],
    avoid: [
      { hex: '#FFB6C1', name: 'icy pink' },
      { hex: '#71C5E8', name: 'glacier blue' },
      { hex: '#FFFFFF', name: 'pure white' },
      { hex: '#84329B', name: 'cool purple' },
      { hex: '#C9CDE2', name: 'periwinkle' },
    ],
  },
  dark_autumn: {
    season: 'dark_autumn',
    label: 'Dark Autumn',
    tagline: 'Deep, warm and smoldering',
    palette: [
      { hex: '#5C4033', name: 'espresso' },
      { hex: '#800020', name: 'burgundy' },
      { hex: '#556B2F', name: 'army olive' },
      { hex: '#8B0000', name: 'oxblood' },
      { hex: '#3B2F2F', name: 'dark cocoa' },
      { hex: '#B8860B', name: 'antique gold' },
      { hex: '#2F4F4F', name: 'deep pine' },
      { hex: '#A0522D', name: 'sienna' },
      { hex: '#704214', name: 'sepia' },
      { hex: '#C19A6B', name: 'fawn' },
    ],
    avoid: [
      { hex: '#FFB6C1', name: 'baby pink' },
      { hex: '#A7E6D7', name: 'seafoam' },
      { hex: '#E3E8EA', name: 'icy gray' },
      { hex: '#FFFFFF', name: 'stark white' },
      { hex: '#00A3E0', name: 'ice blue' },
    ],
  },
};

export const SEASON_LIST = Object.values(SEASONS);
